on: workflow_dispatch
jobs:
  split:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: GoogleCloudPlatform/cloud-foundation-fabric
