on: workflow_dispatch
jobs:
  split:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout local repo
      uses: actions/checkout@v3
      with:
        path: local

    - name: Checkout upstream repo
      uses: actions/checkout@v3
      with:
        repository: GoogleCloudPlatform/cloud-foundation-fabric
        path: upstream
        fetch-depth: 0

    - name: Checkout upstream repo
      uses: actions/checkout@v3
      with:
        repository: GoogleCloudPlatform/cloud-foundation-fabric
        path: upstream
    - name: Split
      run: cd upstream ; ls ; git status ;  git subtree split --prefix modules/folder -b split ; git log split
